# composer
FROM composer:1.8 as composer

WORKDIR /app

COPY composer.json /app
RUN composer install --no-dev


# frontend
FROM node:alpine as frontend

ARG NPM_TOKEN

RUN mkdir -p /app/public/js
WORKDIR /app
COPY package.json webpack.config.js .npmrc ./
COPY src/frontend src/frontend
RUN npm install \
  && npm run build


# target
FROM php:7.2-alpine
# FROM webdevops/php-nginx:alpine

COPY . /app
COPY --from=composer /app/vendor /app/vendor
COPY --from=frontend /app/public/js /app/public/js

EXPOSE 9000

CMD php -S 0.0.0.0:9000 -t /app/public