FROM alpine:3.9

ARG NPM_TOKEN
ENV CACHE_BUSTER=0

RUN apk add --no-cache \
    php7 php7-common php7-opcache \
    curl \
    php7-json \
    php7-openssl \
    php7-phar \
    php7-zlib \
    php7-mbstring \
    php7-xml \
    git \
    unzip \
    nodejs npm

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php \
  && php composer-setup.php --install-dir=/usr/local/bin --filename=composer

WORKDIR /app

COPY . /app
RUN composer install

RUN npm install \
  && npm run build

EXPOSE 9000

ENTRYPOINT php -S 0.0.0.0:9000 -t /app/public